src/Systeo/VenteBundle/Entity/PieceExport.php
<?php

namespace Systeo\VenteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * Piece
 *
 * @ORM\Table(name="piece_export")
 * @ORM\Entity(repositoryClass="Systeo\VenteBundle\Repository\PieceExportRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class PieceExport
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     *
     * @ORM\ManyToOne(targetEntity="Systeo\TierBundle\Entity\Tier")
     * @ORM\JoinColumn(nullable=true)
     * @Assert\NotBlank(message="Vous devez sélectionner une tier!")
     */
    private $tier;
    
    /**
     *
     * @ORM\ManyToOne(targetEntity="Systeo\VenteBundle\Entity\Piece")
     * @ORM\JoinColumn(nullable=true)
     */
    private $piece;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=10)
     */
    private $type;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="date", nullable=true)
     * @Assert\NotBlank(message="Ce champs est obligatoire!")
     */
    private $date;

    /**
     * @var int
     *
     * @ORM\Column(name="numero", type="integer", nullable=true)
     * @Assert\NotBlank(message="Ce champs est obligatoire!")
     */
    private $numero;

    /**
     * @var string
     *
     * @ORM\Column(name="tier_name", type="string", length=255, nullable=true)
     */
    private $tierName;
    
    /**
     * @var string
     *
     * @ORM\Column(name="devise", type="string", length=2, nullable=true)
     *  @Assert\NotBlank(message="Ce champs est obligatoire!")
     */
    private $devise;

    /**
     * @var string
     *
     * @ORM\Column(name="tier_adresse", type="string", length=255, nullable=true)
     */
    private $tierAdresse;

    /**
     * @var string
     *
     * @ORM\Column(name="tier_mf", type="string", length=30, nullable=true)
     */
    private $tierMf;

    /**
     * @var string
     *
     * @ORM\Column(name="montant_ht", type="decimal", precision=10, scale=2, nullable=true)
     * @Assert\NotBlank(message="Ce champs est obligatoire!")
     */
    private $montantHt;

    /**
     * @var string
     *
     * @ORM\Column(name="montant_tva", type="decimal", precision=10, scale=2, nullable=true)
     * @Assert\NotBlank(message="Ce champs est obligatoire!")
     */
    private $montantTva;
    

    /**
     * @var string
     *
     * @ORM\Column(name="montant_ttc", type="decimal", precision=10, scale=2, nullable=true)
     * @Assert\NotBlank(message="Ce champs est obligatoire!")
     */
    private $montantTtc;
    
    /**
    * @ORM\OneToMany(targetEntity="Systeo\VenteBundle\Entity\PieceExportLigne", cascade={"persist","remove"}, mappedBy="pieceExport")
    */
    private $pieceExportLignes;
    
    /**
     * @var bool
     *
     */
    private $lignesAreValid;
    


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type
     *
     * @param string $type
     *
     * @return Piece
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Piece
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set numero
     *
     * @param integer $numero
     *
     * @return Piece
     */
    public function setNumero($numero)
    {
        $this->numero = $numero;

        return $this;
    }

    /**
     * Get numero
     *
     * @return int
     */
    public function getNumero()
    {
        return $this->numero;
    }

    /**
     * Set tierName
     *
     * @param string $tierName
     *
     * @return Piece
     */
    public function setTierName($tierName)
    {
        $this->tierName = $tierName;

        return $this;
    }

    /**
     * Get tierName
     *
     * @return string
     */
    public function getTierName()
    {
        return $this->tierName;
    }

    /**
     * Set tierAdresse
     *
     * @param string $tierAdresse
     *
     * @return Piece
     */
    public function setTierAdresse($tierAdresse)
    {
        $this->tierAdresse = $tierAdresse;

        return $this;
    }

    /**
     * Get tierAdresse
     *
     * @return string
     */
    public function getTierAdresse()
    {
        return $this->tierAdresse;
    }

    /**
     * Set tierMf
     *
     * @param string $tierMf
     *
     * @return Piece
     */
    public function setTierMf($tierMf)
    {
        $this->tierMf = $tierMf;

        return $this;
    }

    /**
     * Get tierMf
     *
     * @return string
     */
    public function getTierMf()
    {
        return $this->tierMf;
    }

    /**
     * Set montantHt
     *
     * @param string $montantHt
     *
     * @return Piece
     */
    public function setMontantHt($montantHt)
    {
        $this->montantHt = $montantHt;

        return $this;
    }

    /**
     * Get montantHt
     *
     * @return string
     */
    public function getMontantHt()
    {
        return $this->montantHt;
    }

    /**
     * Set montantTva
     *
     * @param string $montantTva
     *
     * @return Piece
     */
    public function setMontantTva($montantTva)
    {
        $this->montantTva = $montantTva;

        return $this;
    }

    /**
     * Get montantTva
     *
     * @return string
     */
    public function getMontantTva()
    {
        return $this->montantTva;
    }

    /**
     * Set montantTtc
     *
     * @param string $montantTtc
     *
     * @return Piece
     */
    public function setMontantTtc($montantTtc)
    {
        $this->montantTtc = $montantTtc;

        return $this;
    }

    /**
     * Get montantTtc
     *
     * @return string
     */
    public function getMontantTtc()
    {
        return $this->montantTtc;
    }

    /**
     * Set tier
     *
     * @param \Systeo\TierBundle\Entity\Tier $tier
     *
     * @return Piece
     */
    public function setTier(\Systeo\TierBundle\Entity\Tier $tier = null)
    {
        $this->tier = $tier;

        return $this;
    }

    /**
     * Get tier
     *
     * @return \Systeo\TierBundle\Entity\Tier
     */
    public function getTier()
    {
        return $this->tier;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->pieceLignes = new \Doctrine\Common\Collections\ArrayCollection();
    }

   


    /**
     * Set devise
     *
     * @param string $devise
     *
     * @return PieceExport
     */
    public function setDevise($devise)
    {
        $this->devise = $devise;

        return $this;
    }

    /**
     * Get devise
     *
     * @return string
     */
    public function getDevise()
    {
        return $this->devise;
    }

   

    /**
     * Add pieceExportLigne
     *
     * @param \Systeo\VenteBundle\Entity\PieceExportLigne $pieceExportLigne
     *
     * @return PieceExport
     */
    public function addPieceExportLigne(\Systeo\VenteBundle\Entity\PieceExportLigne $pieceExportLigne)
    {
        $pieceExportLigne->setPieceExport($this);
        $this->pieceExportLignes[] = $pieceExportLigne;

        return $this;
    }

    /**
     * Remove pieceExportLigne
     *
     * @param \Systeo\VenteBundle\Entity\PieceExportLigne $pieceExportLigne
     */
    public function removePieceExportLigne(\Systeo\VenteBundle\Entity\PieceExportLigne $pieceExportLigne)
    {
        $this->pieceExportLignes->removeElement($pieceExportLigne);
    }

    /**
     * Get pieceExportLignes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPieceExportLignes()
    {
        return $this->pieceExportLignes;
    }
    
    /**
     * 
     * @return type
     */
    public function getSolde(){
        return $this->getMontantTtc();
    }
    
    
    public function getreglements(){
        return [];
    }

    /**
     * Set piece
     *
     * @param \Systeo\VenteBundle\Entity\Piece $piece
     *
     * @return PieceExport
     */
    public function setPiece(\Systeo\VenteBundle\Entity\Piece $piece = null)
    {
        $this->piece = $piece;

        return $this;
    }

    /**
     * Get piece
     *
     * @return \Systeo\VenteBundle\Entity\Piece
     */
    public function getPiece()
    {
        return $this->piece;
    }
    
    /**
     * Set lignesAreValid
     *
     * @param boolean $lignesAreValid
     *
     * @return Piece
     */
    public function setLignesAreValid($lignesAreValid)
    {
        $this->lignesAreValid = $lignesAreValid;

        return $this;
    }

    /**
     * Get lignesAreValid
     *
     * @return boolean
     */
    public function getLignesAreValid()
    {
        foreach($this->getPieceExportLignes() as $ligne){
            if(!$ligne->checkIfValid()){
                return false;
            }
        }
        
        return true;
    }
    
    /**
     * @Assert\Callback
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        // check if the name is actually a fake name
        if (!$this->getLignesAreValid()) {
            $context->buildViolation('Tous les champs de toutes les lignes doivent être valides!')
                ->atPath('lignesAreValid')
                ->addViolation();
        }
        
       
        
        
    }
}

src/Systeo/VenteBundle/Form/PieceType.php
<?php

namespace Systeo\VenteBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Systeo\VenteBundle\Form\PieceLigneType;

class PieceType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        
        $em = $options['entity_manager'];
        
        $config = $em->getRepository('SysteoConfigBundle:Config')->findOneById(1);
        
        $builder
                ->add('date', DateType::class, [
                    'label' => "Date",
                    'required' => false,
                    'widget' => 'single_text',
                    'format' => 'dd/MM/yyyy',
                    'attr' => [
                        'autocomplete' => 'off',
                        'placeholder' => "Date",
                        'class' => 'datepicker']])
                ->add('numero', TextType::class, [
                    "label" => 'Numéro',
                    "required" => false,
                    'attr' => [
                        'autocomplete' => 'off',]])
                ->add('tierName', TextType::class, [
                    "label" => 'Raison sociale / Nom Entreprise',
                    "required" => false,
                    'attr' => [
                        'autocomplete' => 'off',]])
                ->add('tierMf', TextType::class, [
                    "label" => 'Matricule fiscale',
                    "required" => false,
                    'attr' => [
                        'autocomplete' => 'off',]])
                ->add('tierAdresse', TextType::class, [
                    "label" => 'Adresse',
                    "required" => false,
                    'attr' => [
                        'autocomplete' => 'off',]])
                ->add('montantHt', TextType::class, [
                    "label" => false,
                    "required" => false,
                    'attr' => [
                        'autocomplete' => 'off',]])
                ->add('montantTva', TextType::class, [
                    "label" => false,
                    "required" => false,
                    'attr' => [
                        'autocomplete' => 'off',]])
                ->add('montantTimbre', TextType::class, [
                    "label" => false,
                    "required" => false,
                    'attr' => [
                        'autocomplete' => 'off',]])
                ->add('montantTtc', TextType::class, [
                    "label" => false,
                    "required" => false,
                    'attr' => [
                        'autocomplete' => 'off',]])
                ->add('tier', EntityType::class, array(
                    'class' => 'SysteoTierBundle:Tier',
                    /*'query_builder' => function(EntityRepository $er) {
                        return $er->createQueryBuilder('t')
                                ->where('t.c = :fournisseur')
                                ->setParameter('fournisseur', true);
                    },*/
                    'choice_label' => 'name',
                    'placeholder' => '',
                    'label' => false,
                    'required' => false))
                ->add('pieceLignes', CollectionType::class, array(
                        'entry_type' => PieceLigneType::class,
                        'allow_add'    => true,
                        'allow_delete' => true,
                        'by_reference' => false,
                        'entry_options'=>[
                            'config'=>$config
                        ],
                    ))
                ->add('lignesAreValid', TextType::class,[
                    "required" => false,
                ])
                ->add('montantFodec', TextType::class, [
                    "label" => false,
                    "required" => false,
                    'attr' => [
                        'autocomplete' => 'off',]])
                
                ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Systeo\VenteBundle\Entity\Piece'
        ));
        
        $resolver->setRequired('entity_manager'); 
        
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'systeo_ventebundle_piece';
    }


}

src/Systeo/VenteBundle/Resources/views/piece/index-affectation.html.twig
{% block body %}
    
    <table class="table table-bordered index_table">
        <thead>
            <tr>
                <th>N°</th>
                <th>Date</th>
                <th class="text-right">Montant TTC</th>
                <th class="text-right">Solde</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for piece in pieces %}
                <tr>
                    <td>{{piece.numero}}</td>
                    <td>{%if piece.date%}{{piece.date|date('d/m/Y')}}{%endif%}</td>
                    <td class='text-right' nowrap>{%if piece.montantTtc%}{{piece.montantTtc|number_format(3, '.', ' ')}}{%endif%}</td>
                    <td class='text-right' nowrap>
                        {%if (piece.solde is not null) and (piece.solde >0) %}
                            <b><span style='color: red;'>
                                {{piece.solde|number_format(3, '.', ' ')}}
                        {%else%}        
                            <b><span style='color: green;'>
                                0.000
                        {%endif%}
                    </td>
                    <td>
                        <a class="btn btn-info btn-xs" href="{{path('piece_export_affecter_local')}}?type=affecter&vue={{vue}}&piece_id={{piece.id}}&piece_export_id={{piece_export_id}}">Affecter</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>  
{% endblock %}

src/Systeo/VenteBundle/Resources/views/piece/show.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
    <script  src="{{asset('bundles/systeovente/js/main.js') }}" ></script> 
    <script  src="{{asset('bundles/systeobanque/js/main.js') }}" ></script>
    <script  src="{{asset('bundles/systeoreglement/js/main.js') }}" ></script>
    <fieldset>
            <legend>Détails {{piece.type}}</legend>
    </fieldset>
    <div class="row">
        <div class="col-lg-12">
            <div class="btn_add pull-right">
                <ul id='show_action_buttons'>
                    <li><a href="{{ path('piece_imprimer_one', { 'id': piece.id }) }}" target="_blank"  class="btn btn-default">Imprimer  <span class="glyphicon glyphicon-print"></a></li>
                    <li><a href="{{ path('piece_index') }}?type={{piece.type}}"  class="btn btn-info">Liste des {{piece.type}}s <span class="glyphicon glyphicon-th-list"></span></a></li>
                    <li><a href="{{ path('piece_edit', { 'id': piece.id }) }}"  class="btn btn-warning">Modifier  <span class="glyphicon glyphicon-edit"></a></li>
                    <li>
                        {{ form_start(delete_form) }}

                        <button class='btn btn-danger delete_form_button' data-msg="Voulez vous vraiement supprimer ce(tte) {{piece.type}} ?" type="button">Supprimer <span class="glyphicon glyphicon-trash"></span></button>
                        {{ form_end(delete_form) }}
                    </li>
                </ul>
            </div>   
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-4">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>Tier / Client</th>
                        <td>{%if piece.tier%}<a href="{{path('tier_show',{'id':piece.tier.id})}}">{{piece.tierName}}</a>{%else%}{{piece.tierName}}{%endif%}</td>
                    </tr>
                    <tr>
                        <th>Code</th>
                        <td>CL-0{{piece.tier.id}}</td>
                    </tr>
                    <tr>
                        <th>Matricule fiscale</th>
                        <td>{{piece.tierMf}}</td>
                    </tr>
                    <tr>
                        <th>Adresse</th>
                        <td>{{piece.tierAdresse}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
                    
        <div class="col-lg-4 col-lg-offset-1">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th class="col-lg-3">Numéro</th>
                        {%set prefix=''%}
                        {%if piece.numero != ""%}
                            {%for i in 0..(3-piece.numero|length)%}
                                {%set prefix=prefix~'0'%}
                            {%endfor%}
                        {%endif%}
                        <td>{{prefix}}{{piece.numero}} / {%if piece.date%}{{piece.date|date('Y')}}{%endif%}</td>
                    </tr>
                    <tr>
                        <th>Date</th>
                        <td>{%if piece.date%}{{piece.date|date('d/m/Y')}}{%endif%}</td>
                    </tr>
                    
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9">
            <table class="table table-bordered">
                <tr>
                    <th style="width: 7%">Code</th>
                    <th style="width: 50%">Désignation</th>
                    <th style="width: 14%" class="text-right">Prix Unit</th>
                    <th style="width: 7%" class="text-center">Qté</th>
                    <th style="width: 7%" class="text-center">TVA</th>
                    <th style="width: 15%" class="text-right">Total HT</th>
                </tr>
                {%for ligne in piece.pieceLignes%}
                    <tr>
                    <td>{{ligne.code}}</td>
                    <td>{{ligne.name|raw}}</td>
                    <td class="text-right" nowrap>{%if ligne.prixHt%}{{ligne.prixHt|number_format(3, '.', ' ')}}{%endif%}</td>
                    <td class="text-center">{{ligne.quantite}}</td>
                    <td class="text-center">{{ligne.tauxTva}}</td>
                    <td class="text-right" nowrap>{%if ligne.totalHt%}{{ligne.totalHt|number_format(3, '.', ' ')}}{%endif%}</td>
                    </tr>
                {%endfor%}
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <table class="table table-striped table-bordered">
                <tr>
                    <th class="text-center">TVA</th>
                    <th class="text-center">Montant</th>
                </tr>
                {%for key,base in base_tva%}
                    {%if base != 0%}
                    <tr>
                        <th class="text-center">{{key}}</th>
                        <td class="text-center" nowrap>{%if base%}{{base|number_format(3, '.', ' ')}}{%endif%}</td>
                    </tr>
                    {%endif%}
                {%endfor%}
            </table>
        </div>
        <div class="col-lg-3 col-lg-offset-3">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Total HT</th>
                    <td class="text-right" nowrap>{%if piece.montantHt%}{{piece.montantHt|number_format(3, '.', ' ')}}{%endif%}</td>
                </tr>
                {% if tauxFodec is not null %}
                <tr>
                    <th>Total Fodec</th>
                    <td class="text-right" nowrap>{%if piece.montantFodec%}{{piece.montantFodec|number_format(3, '.', ' ')}}{%endif%}</td>
                </tr>
                {% endif %}
                <tr>
                    <th>Montant TVA</th>
                    <td class="text-right" nowrap>{%if piece.montantTva%}{{piece.montantTva|number_format(3, '.', ' ')}}{%endif%}</td>
                </tr>
                <tr>
                    <th>Droit de timbre</th>
                    <td class="text-right" nowrap>{%if piece.montantTimbre%}{{piece.montantTimbre|number_format(3, '.', ' ')}}{%endif%}</td>
                </tr>
                <tr>
                    <th>Total TTC</th>
                    <td class="text-right" nowrap>{%if piece.montantTtc%}{{piece.montantTtc|number_format(3, '.', ' ')}}{%endif%}</td>
                </tr>
                <tr>
                    <th>Solde</th>
                    <td class="text-right" nowrap>
                        {%if (piece.solde is not null) and (piece.solde >0) %}
                            <b><span style='color: red;'>
                                {{piece.solde|number_format(3, '.', ' ')}}
                        {%else%}        
                            <b><span style='color: green;'>
                                0.000
                        {%endif%}
                        </span></b>    
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9">
            <h4>Liste des réglements</h4>
            <div class="pull-right">
                <span class="btn btn-success modal-regelement" data-label="Ajouter réglement" data-url="{{path('reglement_new_ajax')}}?type=piece&entite={{piece.id}}">Ajouter Réglement</span>
                <span class="btn btn-primary affecter-reglement" data-url='{{path('banqueoperation_index')}}?origin_vue=piece&origin_vue_id={{piece.id}}'>Affecter Réglement</span>
            </div>
            <div class="clear-both"></div>
            <br />
            {%if piece.reglements%}
                <table class="table table-bordered">
                    <tr>
                        <th>Libellé</th>
                        <th class="text-right">Montant</th>
                        <th>Type</th>
                        <th>Date</th>
                        <th>Banque/Caisse</th>
                        <th>Action</th>
                    </tr>
                    {%set montantTotal = 0%}
                    {%for reg in piece.reglements%}
                        {%set montantTotal = montantTotal + reg.montant%}
                        <tr>
                            <td>{{reg.name}}</td>
                            <td class="text-right">{%if reg.montant%}{{reg.montant|number_format(3, '.', ' ')}}{%endif%}</td>
                            <td>{{reg.type}}</td>
                            <td>{%if reg.date%}{{reg.date|date('d/m/Y')}}{%endif%}</td>
                            <td>
                                
                                {%if reg.BanqueOperation%}
                                    <a class='btn btn-xs btn-danger' href='{{path('reglement_piece_desaffecter_operation_bancaire',{'id':reg.id})}}'>Désaffecter</a> (obc-{{reg.BanqueOperation.id}})
                                {%else%}
                                    <span class="btn btn-xs btn-primary affecter-reglement" data-url='{{path('banqueoperation_index')}}?origin_vue=piece&origin_vue_id={{piece.id}}&origin_type=reglement&origin_type_id={{reg.id}}'>Affecter</span>
                                {%endif%}
                            </td>
                            <td>
                                <ul id="index_action_buttons">
                                    <li><span  data-label="Modifier réglement" data-url="{{path('reglement_edit_ajax',{'id':reg.id})}}?type=piece&entite={{piece.id}}" class="btn btn-xs btn-warning  modal-regelement">Modifier</span></li>
                                    <li><a href='{{path('reglement_show',{'id':reg.id})}}' class="btn btn-xs btn-default">Détails</a></li>
                                </ul>
                            </td>
                        </tr>
                    {%endfor%}
                    <tr>
                        <td></td>
                        <td class="text-right">{{montantTotal|number_format(3, '.', ' ')}}</td>
                        <td colspan="4"></td>
                    </tr>
                </table>
            {%endif%}
        </div>
    </div>
    <div class="modal fade" id="myModalRegelment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalRegelmentLabel"></h4>
                </div>
                <div class="modal-body" id="myModalRegelmentBody">
                    ...
                </div>
                
            </div>
        </div>
    </div>
        
   <div class="modal fade" id="myModalAffectation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="my-modal-large" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalAffectationLabel">Affecter réglement</h4>
                </div>
                <div class="modal-body" id="myModalAffectationBody">
                    ...
                </div>
                
            </div>
        </div>
    </div>
{% endblock %}